### ISSUE TITLE
NuGet PackageReference support planned?

### ISSUE THREAD

**Issue by smoeller-liveid** [OpenSharp/NAutoIt#3]
Hello,
ist the a plan to support the new PackageReference NuGet mode? Currently, it seems not to be supported due to the \lib\ folder not having subfolders per architecture.
Details can be found here: https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference

**Comment by dzmitry-lahoda** [comment]
Please use https://www.nuget.org/packages/AutoItX.Dotnet/
